import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { NextUIProvider } from "@nextui-org/react";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <NextUIProvider>{children}</NextUIProvider>
      </body>
    </html>
  );
}

